name: conifer
recipe: wordpress
config:
  webroot: wp

services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.bash

  node:
    type: node:6.11

    globals:
      newman: "1.3.2"

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.bash'
    description: 'Install and configure WordPress for custom plugin dev'

  newman:
    service: node

  debug:
    service: appserver
    cmd: 'cd /app/wp/wp-content && tail -f debug.log'
    description: 'Get real-time debug log output'

proxy:
  appserver:
    - conifer.lndo.site

  mailhog:
    - mail.conifer.lndo.site
