name: conifer
recipe: wordpress
config:
  webroot: wp

services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install

  node:
    type: node:6.11

    globals:
      newman: "1.3.2"

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.bash'
    description: 'Install and configure WordPress for custom plugin dev'

  newman:
    service: node

  debug:
    service: appserver
    cmd: 'cd /app/wp/wp-content && tail -f debug.log'
    description: 'Get real-time debug log output'

proxy:
  appserver:
    - conifer.lndo.site

  mailhog:
    - mail.conifer.lndo.site

events:
  post-install:
    # ensure WordPress is installed and configured
    - wp --path="$LANDO_MOUNT/wp" plugin uninstall hello akismet
    - wp --path="$LANDO_MOUNT/wp" plugin activate timber-library conifer
    - wp --path="$LANDO_MOUNT/wp" theme activate groot
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyten
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyeleven
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentytwelve
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentythirteen
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyfourteen
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyfifteen
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentysixteen
    - wp --path="$LANDO_MOUNT/wp" theme uninstall twentyseventeen
