name: conifer
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.bash

    overrides:
      services:
        environment:
          # Pass any non-empty CI envvar from the host into Lando
          # This is so we can force non-interactive mode setting up WP
          CI: ${CI:-''}

  database:
    type: mysql:5.7

  node:
    type: node:6.11

    globals:
      newman: "1.3.2"
      yarn: "1.5.1"

    run:
      - cd $LANDO_MOUNT && yarn install

    overrides:
      services:
        image: 'sitecrafting/lando-node-cypress:latest'

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.bash'
    description: 'Install and configure WordPress for custom plugin dev'

  newman:
    service: node

  yarn:
    service: node

  debug:
    service: appserver
    cmd: 'cd /app/wp/wp-content && tail -f debug.log'
    description: 'Get real-time debug log output'

  e2e:
    service: node
    cmd: 'yarn cypress run'
    description: 'Run end-to-end tests'

proxy:
  appserver:
    - conifer.lndo.site

  mailhog:
    - mail.conifer.lndo.site
