language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'


# This part is required!!!
services:
  - docker

# Install all the lando magic and do a sanity check to verify its working
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.39/lando-v3.0.0-beta.39.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

install:
  - composer install --prefer-dist
  - lando start
  - lando yarn install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer test
  - composer sniff
  - lando e2e
